"""
QuantLab Institutional Position Manager.

Manages open and closed trading positions, unrealized/realized PnL accounting,
scaling in (averaging), scaling out (partial close), breakeven triggers, and trailing stops.
"""

from dataclasses import dataclass, field
from enum import Enum
import uuid
from typing import Any, Dict, List, Optional, Tuple


class PositionSide(str, Enum):
    """Position direction."""

    LONG = "LONG"
    SHORT = "SHORT"


@dataclass
class ScalingEvent:
    """Audit record of scaling in or partial scaling out events."""

    timestamp: Any
    event_type: str  # 'SCALE_IN' or 'SCALE_OUT'
    quantity: float
    price: float
    commission: float
    slippage: float
    realized_pnl: float = 0.0


@dataclass
class Position:
    """Dataclass representing an active or closed position."""

    position_id: str
    symbol: str
    side: PositionSide
    quantity: float
    entry_price: float
    current_price: float
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    trailing_stop_pips: Optional[float] = None
    breakeven_pips: Optional[float] = None
    breakeven_offset_pips: float = 0.0
    breakeven_triggered: bool = False
    highest_price: float = field(init=False)
    lowest_price: float = field(init=False)
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0
    total_commission: float = 0.0
    total_slippage: float = 0.0
    opened_at: Any = None
    closed_at: Any = None
    is_open: bool = True
    exit_price: Optional[float] = None
    exit_reason: Optional[str] = None
    scaling_history: List[ScalingEvent] = field(default_factory=list)

    def __post_init__(self) -> None:
        """Initialize price extremums."""
        self.highest_price = self.entry_price
        self.lowest_price = self.entry_price
        self.current_price = self.entry_price

    def update_price(self, price: float) -> None:
        """Update current price and track price extremes for trailing stops."""
        self.current_price = float(price)
        self.highest_price = max(self.highest_price, self.current_price)
        self.lowest_price = min(self.lowest_price, self.current_price)

        # Calculate unrealized PnL
        if self.side == PositionSide.LONG:
            self.unrealized_pnl = (self.current_price - self.entry_price) * self.quantity
        else:
            self.unrealized_pnl = (self.entry_price - self.current_price) * self.quantity

    def scale_in(
        self, add_qty: float, fill_price: float, commission: float = 0.0, slippage: float = 0.0, timestamp: Any = None
    ) -> None:
        """Scale in / add size to existing position, averaging entry price.

        Args:
            add_qty: Quantity to add.
            fill_price: Execution price for new size.
            commission: Commission cost incurred.
            slippage: Slippage cost incurred.
            timestamp: Time of scale in event.
        """
        if add_qty <= 0:
            raise ValueError("add_qty must be positive.")

        total_prev = self.entry_price * self.quantity
        total_new = fill_price * add_qty
        self.quantity += add_qty
        self.entry_price = (total_prev + total_new) / self.quantity
        self.total_commission += commission
        self.total_slippage += slippage

        self.scaling_history.append(
            ScalingEvent(
                timestamp=timestamp,
                event_type="SCALE_IN",
                quantity=add_qty,
                price=fill_price,
                commission=commission,
                slippage=slippage,
            )
        )
        self.update_price(fill_price)

    def scale_out(
        self, reduce_qty: float, exit_price: float, commission: float = 0.0, slippage: float = 0.0, timestamp: Any = None
    ) -> float:
        """Scale out / partial close of position size.

        Args:
            reduce_qty: Quantity to close out.
            exit_price: Execution price for closed fraction.
            commission: Commission cost on partial close.
            slippage: Slippage cost on partial close.
            timestamp: Time of partial close.

        Returns:
            Realized PnL generated by this partial close.
        """
        if reduce_qty <= 0 or reduce_qty > self.quantity:
            raise ValueError("Invalid reduce_qty for partial close.")

        if self.side == PositionSide.LONG:
            pnl = (exit_price - self.entry_price) * reduce_qty
        else:
            pnl = (self.entry_price - exit_price) * reduce_qty

        pnl -= (commission + slippage)
        self.realized_pnl += pnl
        self.total_commission += commission
        self.total_slippage += slippage
        self.quantity -= reduce_qty

        self.scaling_history.append(
            ScalingEvent(
                timestamp=timestamp,
                event_type="SCALE_OUT",
                quantity=reduce_qty,
                price=exit_price,
                commission=commission,
                slippage=slippage,
                realized_pnl=pnl,
            )
        )

        if self.quantity <= 1e-9:
            self.is_open = False
            self.closed_at = timestamp
            self.exit_price = exit_price
            self.exit_reason = "PARTIAL_CLOSE_COMPLETED"

        return pnl

    def check_breakeven(self, high: float, low: float, point_value: float = 0.0001) -> bool:
        """Check and update breakeven stop loss if trigger threshold achieved.

        Args:
            high: Bar high price.
            low: Bar low price.
            point_value: Size of 1 pip.

        Returns:
            True if breakeven was triggered in this check.
        """
        if self.breakeven_triggered or self.breakeven_pips is None:
            return False

        trigger_dist = self.breakeven_pips * point_value
        offset_dist = self.breakeven_offset_pips * point_value

        if self.side == PositionSide.LONG:
            if high - self.entry_price >= trigger_dist:
                new_sl = self.entry_price + offset_dist
                if self.stop_loss is None or new_sl > self.stop_loss:
                    self.stop_loss = new_sl
                    self.breakeven_triggered = True
                    return True
        else:
            if self.entry_price - low >= trigger_dist:
                new_sl = self.entry_price - offset_dist
                if self.stop_loss is None or new_sl < self.stop_loss:
                    self.stop_loss = new_sl
                    self.breakeven_triggered = True
                    return True

        return False

    def update_trailing_stop(self, high: float, low: float, point_value: float = 0.0001) -> bool:
        """Update trailing stop loss level based on price movements.

        Args:
            high: Bar high price.
            low: Bar low price.
            point_value: Pip size.

        Returns:
            True if stop loss level was updated.
        """
        if self.trailing_stop_pips is None:
            return False

        dist = self.trailing_stop_pips * point_value
        updated = False

        if self.side == PositionSide.LONG:
            new_sl = high - dist
            if self.stop_loss is None or new_sl > self.stop_loss:
                self.stop_loss = max(self.entry_price if self.breakeven_triggered else -1e9, new_sl)
                updated = True
        else:
            new_sl = low + dist
            if self.stop_loss is None or new_sl < self.stop_loss:
                self.stop_loss = min(self.entry_price if self.breakeven_triggered else 1e9, new_sl)
                updated = True

        return updated


class PositionManager:
    """Manages collection of open and closed positions across backtest execution."""

    def __init__(self) -> None:
        """Initialize PositionManager."""
        self._open_positions: Dict[str, Position] = {}
        self._closed_positions: List[Position] = []
        self._counter: int = 0

    def open_position(
        self,
        symbol: str,
        side: PositionSide,
        quantity: float,
        entry_price: float,
        stop_loss: Optional[float] = None,
        take_profit: Optional[float] = None,
        trailing_stop_pips: Optional[float] = None,
        breakeven_pips: Optional[float] = None,
        breakeven_offset_pips: float = 0.0,
        commission: float = 0.0,
        slippage: float = 0.0,
        opened_at: Any = None,
    ) -> Position:
        """Open a new position.

        Returns:
            Newly created Position object.
        """
        if quantity <= 0:
            raise ValueError("Position quantity must be positive.")

        self._counter += 1
        pos_id = f"POS-{self._counter:06d}-{uuid.uuid4().hex[:6]}"

        pos = Position(
            position_id=pos_id,
            symbol=symbol,
            side=side,
            quantity=float(quantity),
            entry_price=float(entry_price),
            current_price=float(entry_price),
            stop_loss=float(stop_loss) if stop_loss is not None else None,
            take_profit=float(take_profit) if take_profit is not None else None,
            trailing_stop_pips=float(trailing_stop_pips) if trailing_stop_pips is not None else None,
            breakeven_pips=float(breakeven_pips) if breakeven_pips is not None else None,
            breakeven_offset_pips=float(breakeven_offset_pips),
            total_commission=float(commission),
            total_slippage=float(slippage),
            opened_at=opened_at,
        )

        self._open_positions[pos_id] = pos
        return pos

    def close_position(
        self,
        position_id: str,
        exit_price: float,
        exit_reason: str = "SIGNAL_EXIT",
        commission: float = 0.0,
        slippage: float = 0.0,
        closed_at: Any = None,
    ) -> Position:
        """Close an active open position completely."""
        pos = self._open_positions.get(position_id)
        if not pos:
            raise KeyError(f"Open position '{position_id}' not found.")

        if pos.side == PositionSide.LONG:
            pnl = (exit_price - pos.entry_price) * pos.quantity
        else:
            pnl = (pos.entry_price - exit_price) * pos.quantity

        pnl -= (commission + slippage)
        pos.realized_pnl += pnl
        pos.total_commission += commission
        pos.total_slippage += slippage
        pos.unrealized_pnl = 0.0
        pos.is_open = False
        pos.exit_price = float(exit_price)
        pos.exit_reason = exit_reason
        pos.closed_at = closed_at

        del self._open_positions[position_id]
        self._closed_positions.append(pos)
        return pos

    def partial_close(
        self,
        position_id: str,
        reduce_qty: float,
        exit_price: float,
        commission: float = 0.0,
        slippage: float = 0.0,
        closed_at: Any = None,
    ) -> Tuple[Position, float]:
        """Perform partial close on active position."""
        pos = self._open_positions.get(position_id)
        if not pos:
            raise KeyError(f"Open position '{position_id}' not found.")

        realized_pnl = pos.scale_out(reduce_qty, exit_price, commission, slippage, closed_at)

        if not pos.is_open:
            del self._open_positions[position_id]
            self._closed_positions.append(pos)

        return (pos, realized_pnl)

    def update_positions_on_bar(
        self,
        symbol: str,
        open_p: float,
        high_p: float,
        low_p: float,
        close_p: float,
        point_value: float = 0.0001,
        timestamp: Any = None,
    ) -> List[Tuple[Position, str, float]]:
        """Update all open positions for symbol against current bar OHLC.

        Returns list of (Position, exit_reason, exit_price) tuples for triggered SL/TP exits.
        """
        triggered_exits: List[Tuple[Position, str, float]] = []

        open_list = [p for p in self._open_positions.values() if p.symbol.upper() == symbol.upper()]
        for pos in open_list:
            pos.update_price(close_p)
            pos.check_breakeven(high_p, low_p, point_value)
            pos.update_trailing_stop(high_p, low_p, point_value)

            # Check Stop Loss & Take Profit Triggers
            if pos.side == PositionSide.LONG:
                # Stop Loss check
                if pos.stop_loss is not None and low_p <= pos.stop_loss:
                    fill_price = min(open_p, pos.stop_loss)
                    triggered_exits.append((pos, "STOP_LOSS", fill_price))
                    continue
                # Take Profit check
                if pos.take_profit is not None and high_p >= pos.take_profit:
                    fill_price = max(open_p, pos.take_profit)
                    triggered_exits.append((pos, "TAKE_PROFIT", fill_price))
                    continue
            else:  # SHORT
                # Stop Loss check
                if pos.stop_loss is not None and high_p >= pos.stop_loss:
                    fill_price = max(open_p, pos.stop_loss)
                    triggered_exits.append((pos, "STOP_LOSS", fill_price))
                    continue
                # Take Profit check
                if pos.take_profit is not None and low_p <= pos.take_profit:
                    fill_price = min(open_p, pos.take_profit)
                    triggered_exits.append((pos, "TAKE_PROFIT", fill_price))
                    continue

        return triggered_exits

    def get_open_positions(self, symbol: Optional[str] = None) -> List[Position]:
        """Fetch active open positions."""
        positions = list(self._open_positions.values())
        if symbol:
            positions = [p for p in positions if p.symbol.upper() == symbol.upper()]
        return positions

    def get_closed_positions(self, symbol: Optional[str] = None) -> List[Position]:
        """Fetch closed positions history."""
        if symbol:
            return [p for p in self._closed_positions if p.symbol.upper() == symbol.upper()]
        return list(self._closed_positions)

    def get_all_positions(self) -> List[Position]:
        """Fetch both open and closed positions."""
        return list(self._open_positions.values()) + list(self._closed_positions)

    def clear(self) -> None:
        """Reset internal positions."""
        self._open_positions.clear()
        self._closed_positions.clear()
        self._counter = 0
