"""
QuantLab Walk Forward Validation Runner.

Executes the core Walk Forward sequence:
1. Training Window (In-Sample) dataset extraction.
2. Parameter optimization via BaseOptimizerAdapter.
3. Validation Window (Out-of-Sample) dataset extraction.
4. Backtest execution on OOS dataset using optimized IS parameters.
5. Record IS & OOS performance metrics and step window forward.
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Type
import pandas as pd

from backtesting.backtest_engine import BacktestConfig, BacktestEngine, BacktestResult
from data.market_dataset import MarketDataset
from strategies.base_strategy import BaseStrategy
from walk_forward.optimizer_interface import BaseOptimizerAdapter, GridSearchOptimizerAdapter
from walk_forward.window_generator import WindowSplit


@dataclass
class ValidationStepResult:
    """Dataclass holding results for an individual Walk Forward window iteration step."""

    window_index: int
    train_split: WindowSplit
    best_params: Dict[str, Any]
    is_metrics: Dict[str, Any]
    oos_metrics: Dict[str, Any]
    oos_equity_df: pd.DataFrame
    oos_trades_df: pd.DataFrame
    is_score: float
    oos_score: float


class ValidationRunner:
    """Institutional Walk Forward Validation Loop Execution Manager."""

    def __init__(self, optimizer_adapter: Optional[BaseOptimizerAdapter] = None) -> None:
        """Initialize ValidationRunner."""
        self.optimizer = optimizer_adapter or GridSearchOptimizerAdapter()

    def run_validation_sequence(
        self,
        strategy_cls: Type[BaseStrategy],
        param_grid: Dict[str, List[Any]],
        dataset: MarketDataset,
        windows: List[WindowSplit],
        metric_target: str = "sharpe_ratio",
        config: Optional[BacktestConfig] = None,
    ) -> List[ValidationStepResult]:
        """Run complete Walk Forward train-optimize-validate sequence across all window splits.

        Args:
            strategy_cls: Target BaseStrategy class.
            param_grid: Dictionary of parameter grid variations.
            dataset: MarketDataset container.
            windows: List of WindowSplit objects generated by window generator.
            metric_target: Metric target to optimize on IS data.
            config: Engine BacktestConfig options.

        Returns:
            List of ValidationStepResult objects.
        """
        results: List[ValidationStepResult] = []
        df_full = dataset.data
        asset = dataset.metadata.asset
        timeframe = dataset.metadata.timeframe

        for split in windows:
            # 1. Slice In-Sample (IS) Training Data
            train_df = df_full.iloc[split.train_start_index : split.train_end_index + 1].copy()

            # 2. Run Hyperparameter Optimization on IS Data
            best_params, is_score, is_metrics = self.optimizer.optimize(
                strategy_cls=strategy_cls,
                param_grid=param_grid,
                train_data=train_df,
                asset_symbol=asset,
                metric_target=metric_target,
                config=config,
            )

            # 3. Slice Out-of-Sample (OOS) Validation Data
            val_df = df_full.iloc[split.val_start_index : split.val_end_index + 1].copy()

            # 4. Instantiate Strategy with Best IS Parameters & Backtest on OOS Data
            oos_strategy = strategy_cls(params=best_params)
            val_dataset = MarketDataset(
                data=val_df,
                asset=asset,
                timeframe=timeframe,
                broker=dataset.metadata.broker,
            )

            oos_engine = BacktestEngine(config=config)
            oos_engine.load_dataset(val_dataset)
            oos_engine.load_strategy(oos_strategy)

            oos_res: BacktestResult = oos_engine.start_simulation()
            oos_score = float(oos_res.metrics.get(metric_target, 0.0))

            step_res = ValidationStepResult(
                window_index=split.window_index,
                train_split=split,
                best_params=best_params,
                is_metrics=is_metrics,
                oos_metrics=oos_res.metrics,
                oos_equity_df=oos_res.equity_curve.to_dataframe(),
                oos_trades_df=oos_res.trade_log.to_dataframe(),
                is_score=is_score,
                oos_score=oos_score,
            )

            results.append(step_res)

        return results
