"""
QuantLab Master Research Engine Package.

Provides a scientific quantitative research laboratory for managing, recording,
comparing, validating, scoring, and documenting reproducible trading strategy experiments.
"""

from research.adapters import (
    BacktestExperimentAdapter,
    MLExperimentAdapter,
    MonteCarloExperimentAdapter,
    WalkForwardExperimentAdapter,
)
from research.comparator import Comparator, ComparisonResult
from research.experiment import Experiment, ExperimentStatus
from research.experiment_manager import ExperimentManager
from research.experiment_registry import ExperimentRegistry
from research.exporter import ExperimentExporter
from research.logger import ResearchLogger, get_research_logger
from research.metadata import MetadataExtractor, SystemMetadata
from research.metrics import (
    AnnualReturnMetric,
    AverageLossMetric,
    AverageTradeMetric,
    AverageWinMetric,
    BaseMetric,
    CalmarRatioMetric,
    CommissionImpactMetric,
    ConsecutiveLossesMetric,
    ConsecutiveWinsMetric,
    DailyReturnMetric,
    DrawdownDurationMetric,
    ExpectancyMetric,
    ExpectancyScoreMetric,
    ExposureMetric,
    GrossLossMetric,
    GrossProfitMetric,
    KellyCriterionMetric,
    LargestLossMetric,
    LargestWinMetric,
    LossRateMetric,
    MarketExposureMetric,
    MaxDrawdownMetric,
    MetricsCalculator,
    MonthlyReturnMetric,
    NetProfitMetric,
    PayoffRatioMetric,
    ProfitFactorMetric,
    RecoveryFactorMetric,
    ReturnMetric,
    RiskRewardMetric,
    SharpeRatioMetric,
    SlippageImpactMetric,
    SortinoRatioMetric,
    SQNMetric,
    TradeDurationMetric,
    UlcerIndexMetric,
    VolatilityMetric,
    WinRateMetric,
)
from research.reports import ReportEngine, ResearchReport
from research.reproducibility import ReproducibilityContext, ReproducibilityManager
from research.scorer import ScoreResult, ScoreWeights, Scorer
from research.validator import ValidationResult, ValidationRule, Validator

__all__ = [
    "Experiment",
    "ExperimentStatus",
    "ExperimentManager",
    "ExperimentRegistry",
    "Comparator",
    "ComparisonResult",
    "Validator",
    "ValidationRule",
    "ValidationResult",
    "Scorer",
    "ScoreResult",
    "ScoreWeights",
    "MetricsCalculator",
    "BaseMetric",
    "ProfitFactorMetric",
    "NetProfitMetric",
    "GrossProfitMetric",
    "GrossLossMetric",
    "AverageTradeMetric",
    "PayoffRatioMetric",
    "ExpectancyMetric",
    "SharpeRatioMetric",
    "SortinoRatioMetric",
    "CalmarRatioMetric",
    "RecoveryFactorMetric",
    "UlcerIndexMetric",
    "SQNMetric",
    "KellyCriterionMetric",
    "MaxDrawdownMetric",
    "DrawdownDurationMetric",
    "WinRateMetric",
    "LossRateMetric",
    "AverageWinMetric",
    "AverageLossMetric",
    "LargestWinMetric",
    "LargestLossMetric",
    "ConsecutiveWinsMetric",
    "ConsecutiveLossesMetric",
    "VolatilityMetric",
    "ReturnMetric",
    "AnnualReturnMetric",
    "MonthlyReturnMetric",
    "DailyReturnMetric",
    "CommissionImpactMetric",
    "SlippageImpactMetric",
    "RiskRewardMetric",
    "ExpectancyScoreMetric",
    "TradeDurationMetric",
    "ExposureMetric",
    "MarketExposureMetric",
    "MetadataExtractor",
    "SystemMetadata",
    "ReproducibilityManager",
    "ReproducibilityContext",
    "ExperimentExporter",
    "ReportEngine",
    "ResearchReport",
    "ResearchLogger",
    "get_research_logger",
    "BacktestExperimentAdapter",
    "WalkForwardExperimentAdapter",
    "MonteCarloExperimentAdapter",
    "MLExperimentAdapter",
]
